### ISSUE TITLE
JSON file does not upload

### ISSUE THREAD

**Issue by Stijn19** [shawnbanasick/kade#11]
Dear mister Banasick,

first of all I would like to thank you for making my thesis life way more bearable. Especially now Q-methods have to be from a distance your work is much appreciated.
I have one bit of trouble. I downloaded KADE, but I cannot upload my JSON file in it. If I use the webbrowser version Ken-Q however I do not bump into this problem. Would you know what could be the problem?

Kind regards, Stijn

**Comment by shawnbanasick** [comment]
Thanks @Stijn19 for using KADE and the helpful notification. I've just updated it to version 1.2.1 to deal with this issue. It should import and export JSON files without a problem now.
