### ISSUE TITLE
Statement of need

### ISSUE THREAD

**Issue by davekinkead** [shawnbanasick/kade#2]
Hi @shawnbanasick - I'm reviewing your software for JOSS.  

Could you please make this more explicit - what does KADE do that other opensource q methodology apps don't? Who is the target audience?

**Comment by imaike** [comment]
Hi @davekinkead - Thanks for taking the time to review.  I'll add a section to the paper and readme to address this issue.

**Comment by shawnbanasick** [comment]
@davekinkead  OK, I’ve added some sections to the readme and paper to address the issues related to target audience and contributions of the software. Thanks again for taking the time to review.

**Comment by davekinkead** [comment]
👍
