### ISSUE TITLE
Automated tests

### ISSUE THREAD

**Issue by davekinkead** [shawnbanasick/kade#3]
>  Automated tests: Are there automated tests or manual steps described so that the function of the software can be verified?

Where is the test suite? I'm unable to locate it.

**Comment by imaike** [comment]
The automated tests are written with the Jest test framework. The tests folder is "src/Sections/_tests_". The tests can be run with "yarn run test" from the terminal

**Comment by davekinkead** [comment]
<img width="1093" alt="Screenshot 2019-04-08 18 01 14" src="https://user-images.githubusercontent.com/611877/55738917-5d2e0700-5a28-11e9-8983-54a7b18741dd.png">

👍
