### ISSUE TITLE
 Functionality documentation

### ISSUE THREAD

**Issue by davekinkead** [shawnbanasick/kade#4]
>  Functionality documentation: Is the core functionality of the software documented to a satisfactory level (e.g., API method documentation)?

Is there any functional documentation other than the demonstration? https://github.com/shawnbanasick/kade#start-to-finish-demonstration

**Comment by imaike** [comment]
The repository wiki has documentation for the functionality and is linked from within the app. I'll add a link to the readme to make it easier to find.

**Comment by shawnbanasick** [comment]
I added the link to the readme to make reference manual easier to find.

**Comment by davekinkead** [comment]
👍
