### ISSUE TITLE
Issue with output

### ISSUE THREAD

**Issue by inspire8319** [shawnbanasick/kade#9]
Hi there! Thank you so much for this open source resource for q sort. I have followed the manual and everything seems to be inputed correctly, but when I get to step 7, Output, I receive a message "Select factors for output in the "options" tab" when trying to access "Factor Characteristics", "Factors Table", "Distinguishing Statements", and "Factor Visualizations" tabs. However, I did select and submit 4 factors in the Output tab. Similarly, my excel output file does not contain this data. I'm sure I'm doing something wrong but cannot identify the issue in the manual. Thanks in advance!

**Comment by NicolaMorea** [comment]
Hello,
I am also experiencing the same issue after changing to version 1.2.0. I am using the same data files I was using in the older version, where I was able to see all the output data. 
Using the new version, however, application doesn't seem to register the number of selected factors after clicking on "Submit" in the "Options" tab. As a result, the "Factor characteristics" and the other features in the output section do not appear (see screenshots). The issue does not, however, appear with the Demo data. I am using a MacOs.
Many thanks for the assistance and thank you for this fantastic application!

![Screen Shot 2021-02-01 at 16 45 03](https://user-images.githubusercontent.com/78372208/106489669-ec819580-64ac-11eb-9ad5-6ca6e924db91.png)
![Screen Shot 2021-02-01 at 16 45 09](https://user-images.githubusercontent.com/78372208/106489694-f3a8a380-64ac-11eb-8594-8e9d3bc2980b.png)

**Comment by NicolaMorea** [comment]
Apologies for another message from me. After different attempts, I have noticed the issue appears when extracting factors using PCA.
The problem does not seem to happen when using Centroid Factor Analysis.
Additionally, if the analysis is initially carried out using Centroid Factor Analysis, then reseted using the "Reset Analysis" function in 4.Factors and finally redone using PCA, the output data do appear for the PCA analysis.
I hope this helps.
Nicola

**Comment by shawnbanasick** [comment]
Thanks @inspire8319 and @NicolaMorea for using KADE and for your very helpful information about this bug. I've just updated it to version 1.2.1 to deal with this issue. The output screens should be working correctly now.

**Comment by NicolaMorea** [comment]
Thank you so much Shawn for your help and for allowing us to use KADE, such a great and user-friendly piece of software!

Best wishes,

Nicola



________________________________
Da: Shawn Banasick <notifications@github.com>
Inviato: Sunday, February 21, 2021 3:15:24 AM
A: shawnbanasick/kade <kade@noreply.github.com>
Cc: N. Morea <nm613@cam.ac.uk>; Mention <mention@noreply.github.com>
Oggetto: Re: [shawnbanasick/kade] Issue with output (#9)


Closed #9<https://github.com/shawnbanasick/kade/issues/9>.
